package edu.cit.stathis;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableScheduling
public class StathisApplication {

  public static void main(String[] args) {
    SpringApplication.run(StathisApplication.class, args);
  }
}
